//! Deterministic development dataset shared by the mock seeder and the
//! `FakeGeocoder` (Ledger #1/#2). Never used outside dev/demo workflows.
//!
//! Geography: Curitiba, Paraná. Timezone is still `America/Sao_Paulo` (Curitiba
//! keeps BRT, no DST) — the seeder tags every row with it.

use bikenest_domain::{Cost, CurrencyCode, Money, ParkingType, PricingUnit};

/// One weekly hours row: (iso_day, opens(h,m), closes(h,m), all_day).
pub type HoursRow = (u8, (u32, u32), (u32, u32), bool);

/// Known destinations for the fake geocoder: (normalized query, lat, lon).
/// Keys are stored in the `normalize()`d form (lowercase, accents stripped) so
/// they match the normalized search query.
pub const LANDMARKS: &[(&str, f64, f64)] = &[
    ("rua xv de novembro", -25.429_700, -49.270_500),
    ("boca maldita", -25.429_500, -49.270_000),
    ("praca tiradentes", -25.428_800, -49.271_200),
    ("catedral de curitiba", -25.429_100, -49.271_800),
    ("mercado municipal", -25.435_800, -49.266_200),
    ("largo da ordem", -25.427_000, -49.274_500),
    ("museu oscar niemeyer", -25.409_000, -49.268_000),
    ("mon", -25.409_000, -49.268_000),
    ("jardim botanico", -25.443_000, -49.238_500),
    ("parque barigui", -25.425_800, -49.308_500),
    ("parque tangua", -25.378_800, -49.286_200),
    ("opera de arame", -25.385_500, -49.276_000),
    ("passeio publico", -25.423_000, -49.269_500),
    ("praca do japao", -25.447_000, -49.282_000),
    ("batel", -25.441_500, -49.287_000),
    ("shopping estacao", -25.439_200, -49.264_000),
    ("ufpr", -25.430_000, -49.265_000),
    ("torre panoramica", -25.418_000, -49.290_500),
    ("teatro guaira", -25.431_800, -49.268_800),
    ("curitiba", -25.428_400, -49.273_300),
];

/// One mock parking row (all fields explicit; the seeder inserts exactly this).
#[derive(Debug, Clone)]
pub struct MockParking {
    pub name: &'static str,
    pub address: &'static str,
    pub description: &'static str,
    pub parking_type: ParkingType,
    pub cost: Cost,
    pub lat: f64,
    pub lon: f64,
    /// Weekly hours as (iso_day, opens, closes, all_day); empty = closed all week.
    pub hours: Vec<HoursRow>,
    pub hours_unknown: bool,
    /// (feature_code, state) — 0 unknown, 1 yes, 2 no.
    pub security: Vec<(&'static str, i16)>,
    pub rating_avg: Option<f64>,
    pub rating_count: i64,
    /// Days since last verification (relative to seed time).
    pub verified_days_ago: Option<i64>,
    /// Basename of the seeded photo (under `web/static/img/`) attached to this
    /// location, or `None` for a location with no photo yet. The seeder stores
    /// the file through the object-storage port and links it (moderation
    /// `APPROVED`). See `crates/infrastructure/src/parking/seed.rs`.
    pub photo: Option<&'static str>,
}

fn paid(cents: i64, currency: &str, unit: PricingUnit) -> Cost {
    Cost::Paid {
        price: Some(Money::new(
            cents,
            CurrencyCode::parse(currency).expect("devdata currency"),
            unit,
        )),
    }
}

/// The bike photos bundled under `web/static/img/`, cycled across the dataset so
/// most (but not all) seeded locations show a real image.
const PHOTOS: &[&str] = &[
    "hero-bike-parking.jpg",
    "street-rack-mint-bike.jpg",
    "mtb-pair-rack.jpg",
    "square-bike-rows.jpg",
    "cyclist-foggy-avenue.jpg",
];

/// ~24 locations around Curitiba landmarks, spanning every freshness bucket,
/// cost kind, type, hours shape and security mix (plans/m1-search-map.md §8).
pub fn mock_parkings() -> Vec<MockParking> {
    let full_week = |open: (u32, u32), close: (u32, u32)| {
        (1..=7).map(|d| (d, open, close, false)).collect::<Vec<_>>()
    };
    vec![
        MockParking {
            name: "Paraciclo Rua XV",
            address: "R. XV de Novembro, 300",
            description: "Racks no calçadão, em frente às lojas.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.429_700,
            lon: -49.270_500,
            hours: full_week((0, 0), (23, 59)),
            hours_unknown: false,
            security: vec![("well_lit", 1), ("cctv", 0), ("indoor", 2)],
            rating_avg: None,
            rating_count: 0,
            verified_days_ago: Some(3),
            photo: Some("street-rack-mint-bike.jpg"),
        },
        MockParking {
            name: "Bicicletário MON",
            address: "R. Marechal Hermes, 999",
            description: "Bicicletário coberto no Museu Oscar Niemeyer.",
            parking_type: ParkingType::Indoor,
            cost: paid(1000, "BRL", PricingUnit::Day),
            lat: -25.409_000,
            lon: -49.268_000,
            hours: (1..=6).map(|d| (d, (9, 0), (18, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("indoor", 1),
                ("cctv", 1),
                ("staffed", 1),
                ("controlled_access", 1),
                ("well_lit", 1),
            ],
            rating_avg: Some(4.6),
            rating_count: 12,
            verified_days_ago: Some(1),
            photo: Some("hero-bike-parking.jpg"),
        },
        MockParking {
            name: "Bicicletário Rodoferroviária",
            address: "Av. Pres. Affonso Camargo, 330",
            description: "Acesso pela lateral do terminal; vagas cobertas.",
            parking_type: ParkingType::ParkingFacility,
            cost: Cost::Free,
            lat: -25.439_000,
            lon: -49.261_000,
            hours: (1..=7).map(|d| (d, (5, 0), (22, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("cctv", 1), ("well_lit", 1), ("restricted_access", 1)],
            rating_avg: Some(4.1),
            rating_count: 7,
            verified_days_ago: Some(20),
            photo: Some("square-bike-rows.jpg"),
        },
        MockParking {
            name: "Lockers Shopping Estação",
            address: "Av. Sete de Setembro, 2775",
            description: "Armários individuais com tomada.",
            parking_type: ParkingType::Locker,
            cost: paid(500, "BRL", PricingUnit::Hour),
            lat: -25.439_200,
            lon: -49.264_000,
            hours: vec![
                (1, (6, 0), (21, 0), false),
                (2, (6, 0), (21, 0), false),
                (3, (6, 0), (21, 0), false),
                (4, (6, 0), (21, 0), false),
                (5, (6, 0), (21, 0), false),
            ],
            hours_unknown: false,
            security: vec![
                ("restricted_access", 1),
                ("indoor", 1),
                ("dedicated_locking_point", 1),
            ],
            rating_avg: Some(3.8),
            rating_count: 4,
            verified_days_ago: Some(60),
            photo: None,
        },
        MockParking {
            name: "Parque Barigui Portaria",
            address: "Av. Cândido Hartmann, s/n",
            description: "Racks junto à portaria dos ciclistas.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.425_800,
            lon: -49.308_500,
            hours: (1..=7).map(|d| (d, (5, 0), (23, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 1)],
            rating_avg: Some(4.0),
            rating_count: 9,
            verified_days_ago: Some(75),
            photo: Some("mtb-pair-rack.jpg"),
        },
        MockParking {
            name: "Bicicletário Jardim Botânico",
            address: "R. Eng. Ostoja Roguski, 690",
            description: "Vigia no período diurno, próximo à estufa.",
            parking_type: ParkingType::Secured,
            cost: paid(1500, "BRL", PricingUnit::Month),
            lat: -25.443_000,
            lon: -49.238_500,
            hours: (1..=7).map(|d| (d, (6, 0), (20, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("security_guard", 1),
                ("controlled_access", 1),
                ("cctv", 1),
                ("indoor", 1),
                ("dedicated_locking_point", 1),
            ],
            rating_avg: Some(4.9),
            rating_count: 21,
            verified_days_ago: Some(5),
            photo: Some("hero-bike-parking.jpg"),
        },
        MockParking {
            name: "Mercado Municipal Curitiba",
            address: "Av. Sete de Setembro, 1865",
            description: "Racks no estacionamento dos fornecedores.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.435_800,
            lon: -49.266_200,
            hours: vec![
                (1, (4, 0), (16, 0), false),
                (2, (4, 0), (16, 0), false),
                (3, (4, 0), (16, 0), false),
                (4, (4, 0), (16, 0), false),
                (5, (4, 0), (16, 0), false),
                (6, (4, 0), (14, 0), false),
            ],
            hours_unknown: false,
            security: vec![("cctv", 1), ("well_lit", 0)],
            rating_avg: Some(3.5),
            rating_count: 2,
            verified_days_ago: Some(120),
            photo: Some("street-rack-mint-bike.jpg"),
        },
        MockParking {
            name: "Bikes Largo da Ordem",
            address: "Largo Coronel Enéas, 30",
            description: "Suportes em U no Setor Histórico.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.427_000,
            lon: -49.274_500,
            hours: (1..=7).map(|d| (d, (10, 0), (18, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("staffed", 1)],
            rating_avg: None,
            rating_count: 0,
            verified_days_ago: Some(200),
            photo: None,
        },
        MockParking {
            name: "Bicicletário Praça Tiradentes 24h",
            address: "Praça Tiradentes, s/n",
            description: "Abrigo coberto, aberto o dia todo.",
            parking_type: ParkingType::ParkingFacility,
            cost: Cost::Free,
            lat: -25.428_800,
            lon: -49.271_200,
            hours: vec![
                (1, (0, 0), (23, 59), true),
                (2, (0, 0), (23, 59), true),
                (3, (0, 0), (23, 59), true),
                (4, (0, 0), (23, 59), true),
                (5, (0, 0), (23, 59), true),
                (6, (0, 0), (23, 59), true),
                (7, (0, 0), (23, 59), true),
            ],
            hours_unknown: false,
            security: vec![("cctv", 1), ("well_lit", 1)],
            rating_avg: Some(4.2),
            rating_count: 15,
            verified_days_ago: Some(400),
            photo: Some("cyclist-foggy-avenue.jpg"),
        },
        MockParking {
            name: "Parque Tanguá Bike Hub",
            address: "R. Oswaldo Maciel, s/n",
            description: "Estrutura coberta perto da ciclovia.",
            parking_type: ParkingType::Secured,
            cost: paid(800, "BRL", PricingUnit::Day),
            lat: -25.378_800,
            lon: -49.286_200,
            hours: (1..=7).map(|d| (d, (6, 0), (21, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("controlled_access", 1),
                ("cctv", 1),
                ("dedicated_locking_point", 1),
            ],
            rating_avg: Some(4.4),
            rating_count: 6,
            verified_days_ago: None,
            photo: Some("mtb-pair-rack.jpg"),
        },
        MockParking {
            name: "Arena da Baixada Eventos",
            address: "R. Buenos Aires, 1260",
            description: "Bicicletário apenas em dias de evento.",
            parking_type: ParkingType::Indoor,
            cost: paid(2000, "BRL", PricingUnit::Entry),
            lat: -25.448_500,
            lon: -49.277_000,
            hours: vec![],
            hours_unknown: true,
            security: vec![("security_guard", 1), ("indoor", 1)],
            rating_avg: Some(3.9),
            rating_count: 3,
            verified_days_ago: Some(45),
            photo: None,
        },
        MockParking {
            name: "UFPR Reitoria Racks",
            address: "R. XV de Novembro, 1299",
            description: "Racks na Praça Santos Andrade.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.430_000,
            lon: -49.265_000,
            hours: (1..=6).map(|d| (d, (6, 0), (22, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 1), ("cctv", 0)],
            rating_avg: Some(4.3),
            rating_count: 8,
            verified_days_ago: Some(15),
            photo: Some("square-bike-rows.jpg"),
        },
        MockParking {
            name: "Estacionamento Batel",
            address: "Av. do Batel, 1868",
            description: "Vagas para bikes no pavimento térreo.",
            parking_type: ParkingType::ParkingFacility,
            cost: paid(700, "BRL", PricingUnit::Day),
            lat: -25.441_500,
            lon: -49.287_000,
            hours: (1..=7).map(|d| (d, (0, 0), (23, 59), true)).collect(),
            hours_unknown: false,
            security: vec![("cctv", 1), ("staffed", 1), ("well_lit", 1)],
            rating_avg: Some(3.6),
            rating_count: 5,
            verified_days_ago: Some(95),
            photo: Some("hero-bike-parking.jpg"),
        },
        MockParking {
            name: "BikeLocker Shopping Curitiba",
            address: "R. Brig. Franco, 2300",
            description: "Armários no estacionamento do shopping.",
            parking_type: ParkingType::Locker,
            cost: paid(2500, "BRL", PricingUnit::Month),
            lat: -25.440_500,
            lon: -49.288_000,
            hours: (1..=6).map(|d| (d, (6, 0), (20, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("restricted_access", 1),
                ("indoor", 1),
                ("cctv", 1),
                ("dedicated_locking_point", 1),
                ("controlled_access", 1),
            ],
            rating_avg: Some(4.8),
            rating_count: 11,
            verified_days_ago: Some(2),
            photo: Some("street-rack-mint-bike.jpg"),
        },
        MockParking {
            name: "Paraciclo Sete de Setembro",
            address: "Av. Sete de Setembro, 3000",
            description: "Paraciclo na esquina, junto à ciclofaixa.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.437_000,
            lon: -49.279_000,
            hours: (1..=7).map(|d| (d, (0, 0), (23, 59), true)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 0), ("cctv", 0)],
            rating_avg: None,
            rating_count: 0,
            verified_days_ago: Some(320),
            photo: None,
        },
        MockParking {
            name: "Bicicletário Passeio Público",
            address: "R. Pres. Faria, 51",
            description: "Abrigo com cadeado próprio, na entrada do parque.",
            parking_type: ParkingType::ParkingFacility,
            cost: Cost::Unknown,
            lat: -25.423_000,
            lon: -49.269_500,
            hours: vec![],
            hours_unknown: true,
            security: vec![("indoor", 1)],
            rating_avg: None,
            rating_count: 0,
            verified_days_ago: None,
            photo: None,
        },
        MockParking {
            name: "Paraciclo Praça do Japão",
            address: "R. Mal. Hermes, 762",
            description: "Racks ao lado da praça, bastante movimentada.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.447_000,
            lon: -49.282_000,
            hours: (1..=7).map(|d| (d, (0, 0), (23, 59), true)).collect(),
            hours_unknown: false,
            security: vec![],
            rating_avg: Some(3.0),
            rating_count: 1,
            verified_days_ago: Some(150),
            photo: Some("cyclist-foggy-avenue.jpg"),
        },
        MockParking {
            name: "Bike Point Praça Osório",
            address: "Praça Gen. Osório, s/n",
            description: "Vaga vigiada pelo prédio vizinho.",
            parking_type: ParkingType::Secured,
            cost: paid(600, "BRL", PricingUnit::Day),
            lat: -25.432_000,
            lon: -49.273_500,
            hours: (1..=6).map(|d| (d, (7, 0), (19, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("security_guard", 1),
                ("cctv", 1),
                ("indoor", 1),
                ("well_lit", 1),
            ],
            rating_avg: Some(4.0),
            rating_count: 4,
            verified_days_ago: Some(28),
            photo: Some("mtb-pair-rack.jpg"),
        },
        MockParking {
            name: "Bicicletário Teatro Guaíra",
            address: "R. XV de Novembro, 971",
            description: "Coberto, ao lado do teatro.",
            parking_type: ParkingType::Indoor,
            cost: Cost::Free,
            lat: -25.431_800,
            lon: -49.268_800,
            hours: (2..=7).map(|d| (d, (9, 0), (21, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("staffed", 1), ("indoor", 1), ("well_lit", 1)],
            rating_avg: Some(4.5),
            rating_count: 13,
            verified_days_ago: Some(9),
            photo: Some("hero-bike-parking.jpg"),
        },
        MockParking {
            name: "Racks PUCPR Prado Velho",
            address: "R. Imac. Conceição, 1155",
            description: "Próximo ao paraciclo do campus.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.450_000,
            lon: -49.250_000,
            hours: (1..=6).map(|d| (d, (6, 0), (21, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 1)],
            rating_avg: Some(3.7),
            rating_count: 2,
            verified_days_ago: Some(240),
            photo: None,
        },
        MockParking {
            name: "Bicicletário Terminal Guadalupe",
            address: "R. João Negrão, 340",
            description: "Área coberta no terminal de ônibus.",
            parking_type: ParkingType::ParkingFacility,
            cost: paid(300, "BRL", PricingUnit::Day),
            lat: -25.434_000,
            lon: -49.272_000,
            hours: (1..=7).map(|d| (d, (4, 0), (23, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("cctv", 1), ("restricted_access", 0)],
            rating_avg: Some(3.2),
            rating_count: 6,
            verified_days_ago: Some(70),
            photo: Some("square-bike-rows.jpg"),
        },
        MockParking {
            name: "Suportes Parque São Lourenço",
            address: "R. Mateus Leme, 4700",
            description: "Suportes em U próximos à entrada.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.393_000,
            lon: -49.256_000,
            hours: (1..=7).map(|d| (d, (5, 0), (22, 0), false)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 1), ("security_guard", 0)],
            rating_avg: None,
            rating_count: 0,
            verified_days_ago: Some(30),
            photo: Some("cyclist-foggy-avenue.jpg"),
        },
        MockParking {
            name: "Bike Point Alto da XV",
            address: "R. XV de Novembro, 2500",
            description: "Vagas com ponto de fixação dedicado.",
            parking_type: ParkingType::Secured,
            cost: paid(1200, "BRL", PricingUnit::Month),
            lat: -25.427_000,
            lon: -49.256_000,
            hours: (1..=7).map(|d| (d, (6, 0), (22, 0), false)).collect(),
            hours_unknown: false,
            security: vec![
                ("dedicated_locking_point", 1),
                ("controlled_access", 1),
                ("cctv", 1),
                ("indoor", 1),
            ],
            rating_avg: Some(4.7),
            rating_count: 10,
            verified_days_ago: Some(4),
            photo: Some("street-rack-mint-bike.jpg"),
        },
        MockParking {
            name: "Racks Praça Rui Barbosa",
            address: "Praça Rui Barbosa, s/n",
            description: "Racks na praça, junto aos terminais de ônibus.",
            parking_type: ParkingType::Rack,
            cost: Cost::Free,
            lat: -25.435_000,
            lon: -49.272_000,
            hours: (1..=7).map(|d| (d, (0, 0), (23, 59), true)).collect(),
            hours_unknown: false,
            security: vec![("well_lit", 1)],
            rating_avg: Some(3.9),
            rating_count: 3,
            verified_days_ago: Some(48),
            photo: Some("mtb-pair-rack.jpg"),
        },
    ]
}

/// Deterministic photo assignment used when a mock row leaves `photo` as the
/// sentinel — kept for callers that want a stable image for any index.
pub fn photo_for_index(i: usize) -> &'static str {
    PHOTOS[i % PHOTOS.len()]
}
