[package]
name = "bikenest-application"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
base64 = "0.22"
bikenest-domain = { version = "0.1.0", path = "../domain" }
chrono = "0.4"
chrono-tz = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[dev-dependencies]
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
