[package]
name = "bikenest-test-support"
version.workspace = true
edition.workspace = true

[dependencies]
bikenest-domain = { version = "0.1.0", path = "../domain" }
bikenest-infrastructure = { version = "0.1.0", path = "../infrastructure" }
bikenest-test-macros = { version = "0.1.0", path = "../test-macros" }
chrono = "0.4"
chrono-tz = "0.10"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "migrate", "chrono"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
