[package]
name = "bikenest-test-support"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bikenest-application = { workspace = true }
bikenest-domain = { workspace = true }
bikenest-infrastructure = { workspace = true }
bikenest-test-macros = { version = "0.1.0", path = "../test-macros" }
chrono = { workspace = true }
chrono-tz = "0.10"
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
